from bot.loader import cursor

strings = {
    "uk": {
        "fcert": "безкоштовний сертифікат",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Отправьте свой ключ или купите у @gyke69.",
        "start_choice": "Виберіть одну із опцій нижче.",
        "lang_choice": "Виберіть мову нижче: ",
        "lang_changed": "Мову вибрано!",
        "send_p12": "Надішліть .p12 файл.⌛",
        "wrong_p12": "Будь ласка відправте .p12 файл!🫣\nСпробуйте ще раз відправивши .p12 файл.",
        "send_prov": "Надішліть .mobileprovision файл.",
        "wrong_prov": "Будь ласка відправте .mobileprovision файл!🫣\nСпробуйте ще раз відправивши .mobileprovision файл.",
        "downloading_file": "Завантажую файл....",
        "send_pass": "Відправте мені пароль.🔒\nЯкщо ваш сертифікат не має паролю нажміть кнопку пропустити.🔑",
        "skip": "Пропустити",
        "pass_skipped": "Пароль пропущений!",
        "send_ipa": "Надішліть .ipa файл.",
        "wrong_ipa": "Будь ласка, надішліть файл .ipa!",
        "signing": "Підписання фалйу!📝\nЦе може зайняти кілька секунд.",
        "sign_error": "Щось пішло не так.\nПомилка:\n",
        "upload_failed": "Не вдалося завантажити файл!🥹 Спробуйте ще раз.",
        "sign_ok": "Файл підписаний.🟢\nПосилання дійсне 1 тиждень.",
        "install": "Встановити ✅",
        "thanks": "Дякую за використання!",
        "timeout": "Таймаут! Повторіть спробу з початку.",
        "send_udid": "Надішліть UDiD",
        "invalid_udid": "Помилка: недійсний UDiD!",
        "udid_not_found": "Цей UDiD не зареєстрований у нас: \n UDiD: {udid}",
        "status": "Статус",
        "udid_enabled": "Активний 🟢",
        "udid_processing": "В процессі 🟠",
        "udid_ineligible": "В процессі 🔴",
        "register_time": "Час реєстрації",
        "activation_time": "Активується через",
        "checking_udids": "Перевірка UDiD ⌛.",
        "sending_request": "Запит обробляється...",
        "cert_revoked": "Ваш сертифікат було відкликано!🔴\nСпобуйте ще раз з іншим сертифікатом.",
        "invalid_pass": "Ви ввели неправильний пароль!🔒🥹",
        "unknown_error": "Невідома помилка при перевірці сертифікату.🫣",
        "cancel": "Відмінено.",
        "cert_name": "Назва сертифікату",
        "cert_status": "Статус",
        "cert_date": "Термін дії",
        "status_revoked": "Відкликано 🔴",
        "status_signed": "Підписано 🟢",
        "sign_file": "Підписати файл",
        "check_udid": "Перевірити UDiD",
        "pick_cert": "Виберіть сертифікат нижче: ",
        "change_bundle": "Змінити BundleID",
        "additional_opt": "Виберіть додаткові опції нижче: ",
        "new_bundle": "Нажміть на Випадковий чи\nвідправте ваш власний bundleID.",
        "random": "Випадковий",
        "sign_butt": "Підписати iPA",
        "check_cert": "Перевірити сертифікат",
        "rm_key": "Видаляю клавіатру..",
        "changed_bundle": "BundleID встановлено.✅",
        "etc": "Інший",
        "get_cert": "Отримати сертифікат",
        "save_cert": "Зберегти сертифікат",
        "gen_cert": "⏳",
        "gen_err": "Виникла помилка при генерації сертифікату. 🥹\n Будь-ласка зверніться до продавця сертифікату.",
        "my_certs": "Мої сертифікати",
        "saved_cert": "Сертифікат збережено до Моїх Сертифікатів.✅",
        "your_cert": "Ваші сертифікати",
        "added_cert": "Сертифікак додано.✅",
        "back": "Назад",
        "del": "Видалити",
        "del_cert": "Сертифікат видалено.🗑️",
        "add": "Додати",
        "password": "Пароль",
        "skipped": "Пропущен",
        "coupon_count": "Скільки купонів потрібно сгенерувати?",
        "reg_udid": "Зареєструвати UDiD",
        "reg_udid_err": "При реєстрації  UDiD виникла помилка.",
        "reg_udid_success": "Зареєстровано успішно",
        "send_coupon": "Відправте ваш купон",
        "valid_coupon": "Купон правильний!\nБудь ласка UDiD для реєстрації.",
        "invalid_coupon": "Ваш код купона не правильний!",
        "regd_udid": "Успішно зареєстровано!",
        "multi_reg_err": "Вам не дозволено реєструвати більше одного UDiD за один раз!",
        "digit_err": "Помилка, будь ласка відправте цифру.",
        "sellect_acct": "Виберіть аккаунт розробника із списку нижче:",
        "gen_coupon": "Сгенерувати купон",
        "list_accounts": "Список аккаунтів",
        "reg_status": "Статус реєстрації",
        "device": "Пристрій"
    },
    "ru": {
	"fcert": "Бесплатный сертификат",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",        
        "start_choice": "Выберете одну из опций ниже.",
        "send_api_key": "",
        "lang_choice": "Выберете язык ниже: ",
        "lang_changed": "Язык изменнён!",
        "send_p12": "Отправтье .p12 файл.⌛",
        "wrong_p12": "Пожайлуста отправьте .p12 файл!🫣\nПопробуйте ещё раз отправив .p12 файл.",
        "send_prov": "Отправтье .mobileprovision файл.",
        "wrong_prov": "Пожайлуста отправьте .mobileprovision файл!🫣\nПопробуйте ещё раз отправив .mobileprovision файл.",
        "downloading_file": "Загружаю файл...|📁",
        "send_pass": "Отправьте мне пароль.🔒\nЕсли на вашем сертификате нету пароля нажмите кнопку пропустить.🔑",
        "skip": "Пропустить",
        "pass_skipped": "Пароль пропущен!",
        "send_ipa": "Отправьте .ipa файл.",
        "wrong_ipa": "Отправьте файл .ipa!🫣",
        "signing": "Подписание.📝\nЭто может занять несколько секунд.",
        "sign_error": "Что-то пошло не так.\nОшибка:\n",
        "upload_failed": "Не удалось выгрузить файл!🥹 Повторите попытку.",
        "sign_ok": "Файл подписан.🟢\nСсылка действительна 1 неделя.",
        "install": "Установить ✅",
        "thanks": "Спасибо за использование!",
        "timeout": "Тайм-аут! Повторите попытку с начала.",
        "send_udid": "Отправьте UDiD",
        "invalid_udid": "Ошибка: неверный UDiD!",
        "udid_not_found": "Этот UDiD не зарегистрирован у нас:🤷🏻‍♂️ \nUDiD: {udid}",
        "status": "Статус",
        "udid_enabled": "Активный 🟢",
        "udid_processing": "В процессе 🟠",
        "udid_ineligible": "В процессе 🔴",
        "register_time": "Время регистрации",
        "activation_time": "Активируется через",
        "checking_udids": "Проверка UDiD ⌛.",
        "sending_request": "Выполняется запрос...",
        "cert_revoked": "Ваш сертификат был отозван!🔴\nПопробуйте ещё раз с другим сертификатом.",
        "invalid_pass": "Вы ввели неправилный пароль!🔒🥹",
        "unknown_error": "Неизвестная ошибка при проверке сертификата.🫣",
        "cert_name": "Имя сертификата",
        "cert_status": "Статус",
        "cert_date": "Срок сертифката",
        "status_revoked": "Отозван 🔴",
        "status_signed": "Подписан 🟢",
        "cancel": "Отменено.",
        "sign_file": "Подписать iPA",
        "check_udid": "Проверить UDiD",
        "check_cert": "Проверка сертификата",
        "pick_cert": "Выберите сертификат ниже: ",
        "change_bundle": "Изменить BundleID",
        "changed_bundle": "BundleID установлен.✅",
        "additional_opt": "Выберите дополнительные опции ниже: ",
        "new_bundle": "Нажмите на Случайный или\n отправьте свой BundleID",
        "random": "Случайный",
        "sign_butt": "Подписать iPA",
        "rm_key": "Удаление клавиатуры..",
        "etc": "Другой",
        "get_cert": "Получить сертификат",
        "save_cert": "Сохранить сертификат",
        "gen_cert": "⏳",
        "gen_err": "При создании сертификата произошла ошибка. 🥹\n Пожалуйста, свяжитесь с продавцом сертификата.",
        "my_certs": "Мои сертификаты",
        "saved_cert": "Сертификат сохранен в Мои сертифкаты.✅",
        "your_cert": "Ваши сертифкаты",
        "added_cert": "Сертификат добавлен.✅",
        "back": "Назад",
        "del": "Удалить",
        "del_cert": "Сертификат удалён.🗑️",
        "add": "Добавить",
        "password": "Пароль",
        "skipped": "Пропущен",
        "coupon_count": "Сколько купонов нужно сгенерировать?",
        "reg_udid": "Зарегистрировать UDiD",
        "reg_udid_err": "Произошла ошибка при регистрации UDiD.",
        "reg_udid_success": "Зарегестрировано успешно",
        "send_coupon": "Отправьте ваш купон",
        "valid_coupon": "Купон считан!\nПожайлуста отправьте UDiD для регистрации.",
        "invalid_coupon": "Ваш код купона не верный!",
        "regd_udid": "Успешно зарегистрировано!",
        "multi_reg_err": "Вам не разрешено регистрировать больше одного UDiD за раз!",
        "digit_err": "Ошибка, пожалуйста отправьте цифру.",
        "sellect_acct": "Выберете аккаунт разработчика из списка ниже:",
        "gen_coupon": "Сгенерировать купон",
        "list_accounts": "Список аккаунтов",
        "reg_status": "Статус регистрации",
        "device": "Устройство"
    },
    "en": {
	"fcert": "Free Cert",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Send your key or buy from @gyke69",
        "start_choice": "Choose one of the options below.",
        "lang_choice": "Choose your language:",
        "lang_changed": "Language has been changed!",
        "send_p12": "Send me the .p12 file.⌛",
        "wrong_p12": "Please send only .p12 files!🫣\nRetry by continuing to send the .p12 file.",
        "send_prov": "Send the .mobileprovision file.",
        "wrong_prov": "Invalid file type.🫣! \nPlease send a valid (.mobileProvision) file or its URL.",
        "downloading_file": "Uploading your file...|📁",
        "send_pass": "Send me the password.🔒\nIf your certificate doesn't have a password, tap the (Skip Password) button.🔑",
        "skip": "Skip Password",
        "pass_skipped": "Password has been skipped!",
        "send_ipa": "Forward or upload your IPA file.",
        "wrong_ipa": "Invalid file type.🫣! \nPlease send a valid (.ipa) file.",
        "signing": "Signing it. 📝\nThis might take a while.",
        "sign_error": "Something went wrong.\nError:\n",
        "upload_failed": "Failed to upload file! Please retry. 🥹",
        "sign_ok": "IPA file has been signed.🟢\nDownload link is valid for 1 week.",
        "install": "INSTALL ✅",
        "thanks": "Thank you for using it!",
        "timeout": "Timeout! Please retry from the start.",
        "send_udid": "Send me your UDID",
        "invalid_udid": "Error: Invalid UDID!",
        "udid_not_found": "The following UDID is not registered with us:🤷🏻‍♂️ \nUDID: {udid}",
        "status": "Status",
        "udid_enabled": "ACTIVE 🟢",
        "udid_processing": "PROCESSING 🟠",
        "udid_ineligible": "INELIGIBLE 🔴",
        "register_time": "Registered at",
        "activation_time": "Activates in",
        "checking_udids": "⌛",
        "cert_revoked": "Your certificate has been revoked!🔴 \nTry again with a different certificate.",
        "invalid_pass": "You entered the wrong password!🔒🥹",
        "unknown_error": "An unknown error occurred while verifying the certificate.🫣",
        "cert_name": "Certificate name",
        "cert_status": "Status",
        "cert_date": "Expiration Date",
        "status_revoked": "Revoked 🔴",
        "status_signed": "Signed 🟢",
        "cancel": "Canceled.🚪",
        "sign_file": "SIGN IPA",
        "check_udid": "UDID Checker",
        "check_cert": "Revoke Checker",
        "pick_cert": "Choose your certificate below: ",
        "change_bundle": "Change BundleID",
        "additional_opt": "Choose additional options below: ",
        "new_bundle": "Tap on the Random button or\nsend your desired bundleID.",
        "random": "Random",
        "sign_butt": "SIGN IPA",
        "rm_key": "Removing keyboard..",
        "changed_bundle": "BundleID set.✅",
        "etc": "Other",
        "get_cert": "Get Certificate",
        "save_cert": "Save Certificate",
        "gen_cert": "⏳",
        "gen_err": "An error occurred while generating the Certificate. 🥹\n Please contact your Certificate issuer.",
        "my_certs": "My Certificates",
        "saved_cert": "Certificate saved to My Certificates.✅",
        "your_cert": "Your Certificates",
        "added_cert": "Certificate added.✅",
        "back": "Back",
        "del": "Delete",
        "del_cert": "Certificate deleted.🗑️",
        "add": "Add",
        "password": "Password",
        "skipped": "Skipped",
        "coupon_count": "How many coupons would you like me to generate?",
        "reg_udid": "Register UDID",
        "reg_udid_err": "An error occurred while registering your UDID.",
        "reg_udid_success": "Registered Successfully",
        "send_coupon": "Send your Coupon",
        "valid_coupon": "Coupon is valid!\n Please send a UDID to register.",
        "invalid_coupon": "Your coupon code is invalid",
        "regd_udid": "Registered successfully!",
        "multi_reg_err": "You're not allowed to register more than 1 UDID at the same time!",
        "digit_err": "Error, please send a number.",
        "sellect_acct": "Select a developer account from the list below:",
        "gen_coupon": "Generate Coupon",
        "list_accounts": "List Accounts",
        "reg_status": "Register status",
        "device": "Device"
        },
    "fa": {
	"fcert": "Бесплатный сертификат",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Send your key or buy from @gyke69",
        "start_choice": "یکی از گزینه‌های زیر را انتخاب کنید.",
        "lang_choice": "زبان خود را انتخاب کنید:",
        "lang_changed": "زبان تغییر کرد!",
        "send_p12": "فایل .p12 را برای من ارسال کنید.⌛",
        "wrong_p12": "لطفاً فقط فایل .p12 را ارسال کنید!🫣\nمجدداً با ارسال فایل .p12 ادامه دهید.",
        "send_prov": "فایل .mobileprovision را ارسال کنید.",
        "wrong_prov": "نوع فایل نامعتبر است.🫣! \nلطفاً فایل معتبر (.mobileProvision) یا آدرس اینترنتی آن را ارسال کنید.",
        "downloading_file": "در حال بارگذاری فایل شما...|📁",
        "send_pass": "رمز عبور را برای من ارسال کنید.🔒\nاگر گواهی شما رمز عبور ندارد، دکمه (رد کردن رمز) را فشار دهید.🔑",
        "skip": "رد کردن رمز",
        "pass_skipped": "رمز عبور رد شد!",
        "send_ipa": "فایل iPA خود را فروارد یا بارگذاری کنید.",
        "wrong_ipa": "نوع فایل نامعتبر است.🫣! \nلطفاً فایل معتبر (.ipa) را ارسال کنید.",
        "signing": "در حال امضای فایل. 📝\nاین فرایند ممکن است مدتی طول بکشد.",
        "sign_error": "مشکلی پیش آمد.\nخطا:\n",
        "upload_failed": "بارگذاری فایل ناموفق بود! دوباره تلاش کنید. 🥹",
        "sign_ok": "فایل iPA امضا شد.🟢\nلینک دانلود برای 1 هفته معتبر است.",
        "install": "نصب ✅",
        "thanks": "استفاده از این ابزار را به شما تشکر می‌کنیم!",
        "timeout": "مهلت زمانی به پایان رسید! لطفاً مجدداً شروع کنید.",
        "send_udid": "لطفاً UDiD خود را برای ما ارسال کنید.",
        "invalid_udid": "خطا: UDiD نامعتبر است!",
        "udid_not_found": "UDiD زیر با ما ثبت نشده است:🤷🏻♂️ \nUDiD: {udid}",
        "status": "وضعیت",
        "udid_enabled": "فعال 🟢",
        "udid_processing": "در حال پردازش 🟠",
        "udid_ineligible": "غیر مجاز 🔴",
        "register_time": "ثبت شده در",
        "activation_time": "فعال می‌شود در",
        "checking_udids": "در حال بررسی UDiD ها...⌛",
        "cert_revoked": "گواهی شما لغو شده است!🔴 \nلطفاً با گواهی متفاوتی مجدداً تلاش کنید.",
        "invalid_pass": "رمز عبور اشتباه وارد شده است!🔒🥹",
        "unknown_error": "در حین تأیید گواهی خطایی ناشناخته رخ داده است.🫣",
        "cert_name": "نام گواهی",
        "cert_status": "وضعیت",
        "cert_date": "تاریخ انقضا",
        "status_revoked": "لغو شده 🔴",
        "status_signed": "امضا شده 🟢",
        "cancel": "لغو شد.🚪",
        "sign_file": "امضای iPA",
        "check_udid": "بررسی UDiD",
        "check_cert": "بررسی لغو گواهی",
        "pick_cert": "گواهی خود را انتخاب کنید: ",
        "change_bundle": "تغییر BundleID",
        "additional_opt": "گزینه‌های اضافی را انتخاب کنید: ",
        "new_bundle": "روی دکمه تصادفی کلیک کنید یا\nباندل آیدی مورد نظر خود را ارسال کنید.",
        "random": "تصادفی",
        "sign_butt": "SIGN iPA",
        "rm_key": "حذف صفحه کلید..",
        "changed_bundle": "BundleID تنظیم شده.✅",
        "etc": "سایر",
        "get_cert": "دریافت گواهی",
        "save_cert": "ذخیره گواهی",
        "gen_cert": "⏳",
        "gen_err": "خطایی در هنگام تولید گواهی رخ داده است.🥹\n لطفا با صادر کننده گواهی خود تماس بگیرید.",
        "my_certs": "گواهی‌های من",
        "saved_cert": "گواهی در گواهی‌های من ذخیره شد.✅",
        "your_cert": "گواهی‌های شما",
        "added_cert": "گواهی اضافه شد.✅",
        "back": "بازگشت",
        "del": "حذف",
        "del_cert": "گواهی حذف شد.🗑️" ,
        "add": "اضافه کردن",
        "password": "رمز عبور",
        "skipped": "رد شد",
        "coupon_count": "چند کد تخفیف می‌خواهید تولید شود؟",
        "reg_udid": "ثبت UDiD",
        "reg_udid_err": "هنگام ثبت UDiD شما خطایی رخ داد.",
        "reg_udid_success": "ثبت با موفقیت انجام شد",
        "send_coupon": "کد تخفیف خود را ارسال کنید",
        "valid_coupon": "کد تخفیف معتبر است!\n لطفاً یک UDiD برای ثبت ارسال کنید.",
        "invalid_coupon": "کد تخفیف شما نامعتبر است",
        "regd_udid": "با موفقیت ثبت شد!",
        "multi_reg_err": "شما مجاز به ثبت بیش از یک UDiD در همان زمان نیستید!",
        "digit_err": "خطا، لطفاً یک عدد ارسال کنید.",
        "sellect_acct": "حساب توسعه‌دهنده را از فهرست زیر انتخاب کنید:",
        "gen_coupon": "تولید کد تخفیف",
        "list_accounts": "لیست حساب‌ها",
        "reg_status": "وضعیت ثبت",
        "device": "دستگاه"
        },
    "de": {
	"fcert": "Бесплатный сертификат",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Send your key or buy from @gyke69",
        "start_choice": "Wählen Sie eine der unten stehenden Optionen.",
        "lang_choice": "Wählen Sie Ihre Sprache:",
        "lang_changed": "Sprache wurde geändert!",
        "send_p12": "Schicken Sie mir die .p12 Datei.⌛",
        "wrong_p12": "Bitte senden Sie nur .p12 Dateien!🫣\nVersuchen Sie es erneut, indem Sie die .p12 Datei senden.",
        "send_prov": "Senden Sie die .mobileprovision Datei.",
        "wrong_prov": "Ungültiger Dateityp.🫣! \nBitte senden Sie eine gültige (.mobileProvision) Datei oder ihre URL.",
        "downloading_file": "Ihre Datei wird hochgeladen...|📁",
        "send_pass": "Schicken Sie mir das Passwort.🔒\nWenn Ihr Zertifikat kein Passwort hat, tippen Sie auf den Button (Passwort überspringen).🔑",
        "skip": "Passwort überspringen",
        "pass_skipped": "Passwort wurde übersprungen!",
        "send_ipa": "Weiterleiten oder Hochladen Ihrer IPA Datei.",
        "wrong_ipa": "Ungültiger Dateityp.🫣! \nBitte senden Sie eine gültige (.ipa) Datei.",
        "signing": "Es wird signiert. 📝\nDas kann eine Weile dauern.",
        "sign_error": "Etwas ist schief gelaufen.\nFehler:\n",
        "upload_failed": "Hochladen der Datei fehlgeschlagen! Bitte versuchen Sie es erneut. 🥹",
        "sign_ok": "IPA Datei wurde signiert.🟢\nDownload-Link ist für 1 Woche gültig.",
        "install": "INSTALLIEREN ✅",
        "thanks": "Danke, dass Sie es nutzen!",
        "timeout": "Zeitüberschreitung! Bitte versuchen Sie es erneut von Anfang an.",
        "send_udid": "Schicken Sie mir Ihre UDID",
        "invalid_udid": "Fehler: Ungültige UDID!",
        "udid_not_found": "Die folgende UDID ist nicht bei uns registriert:🤷🏻‍♂️ \nUDID: {udid}",
        "status": "Status",
        "udid_enabled": "AKTIV 🟢",
        "udid_processing": "IN BEARBEITUNG 🟠",
        "udid_ineligible": "NICHT BERECHTIGT 🔴",
        "register_time": "Registriert um",
        "activation_time": "Aktiviert in",
        "checking_udids": "⌛",
        "cert_revoked": "Ihr Zertifikat wurde widerrufen!🔴 \nVersuchen Sie es erneut mit einem anderen Zertifikat.",
        "invalid_pass": "Sie haben ein falsches Passwort eingegeben!🔒🥹",
        "unknown_error": "Ein unbekannter Fehler ist beim Überprüfen des Zertifikats aufgetreten.🫣",
        "cert_name": "Zertifikatsname",
        "cert_status": "Status",
        "cert_date": "Ablaufdatum",
        "status_revoked": "Widerrufen 🔴",
        "status_signed": "Signiert 🟢",
        "cancel": "Abgebrochen.🚪",
        "sign_file": "SIGNIERE IPA",
        "check_udid": "UDID Checker",
        "check_cert": "Revokierung Checker",
        "pick_cert": "Wählen Sie Ihr Zertifikat unten: ",
        "change_bundle": "Ändern Sie BundleID",
        "additional_opt": "Wählen Sie zusätzliche Optionen unten: ",
        "new_bundle": "Tippen Sie auf Zufällig oder\nsenden Sie Ihre gewünschte BundleID.",
        "random": "Zufällig",
        "sign_butt": "SiGN iPA",
        "rm_key": "Entferne Tastatur..",
        "changed_bundle": "BundleID wurde gesetzt.✅",
        "etc": "Sonstiges",
        "get_cert": "Holen Sie sich das Zertifikat",
        "save_cert": "Zertifikat speichern",
        "gen_cert": "⏳",
        "gen_err": "Ein Fehler ist beim Generieren des Zertifikats aufgetreten. 🥹\nBitte wenden Sie sich an den Aussteller Ihres Zertifikats.",
        "my_certs": "Meine Zertifikate",
        "saved_cert": "Zertifikat wurde in Meine Zertifikate gespeichert.✅",
        "your_cert": "Ihre Zertifikate",
        "added_cert": "Zertifikat hinzugefügt.✅",
        "back": "Zurück",
        "del": "Löschen",
        "del_cert": "Zertifikat gelöscht.🗑️",
        "add": "Hinzufügen",
        "password": "Passwort",
        "skipped": "Übersprungen",
        "coupon_count": "Wie viele Coupons möchten Sie generieren lassen?",
        "reg_udid": "Registrieren Sie UDID",
        "reg_udid_err": "Ein Fehler ist beim Registrieren Ihrer UDID aufgetreten.",
        "reg_udid_success": "Erfolgreich registriert",
        "send_coupon": "Schicken Sie Ihren Coupon",
        "valid_coupon": "Coupon ist gültig!\nBitte senden Sie eine UDID zur Registrierung.",
        "invalid_coupon": "Ihr Coupon-Code ist ungültig",
        "regd_udid": "Erfolgreich registriert!",
        "multi_reg_err": "Es ist nicht erlaubt, mehr als 1 UDID gleichzeitig zu registrieren!",
        "digit_err": "Fehler, bitte senden Sie eine Zahl.",
        "sellect_acct": "Wählen Sie ein Entwicklerkonto aus der untenstehenden Liste:",
        "gen_coupon": "Coupon generieren",
        "list_accounts": "Konten auflisten",
        "reg_status": "Registrierungsstatus",
        "device": "Gerät"
    },
    "tr": {
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "start_choice": "Aşağıdaki seçeneklerden birini seçin.",
        "lang_choice": "Dilinizi seçin:",
        "lang_changed": "Dil değiştirildi!",
        "send_p12": ".p12 dosyasını bana gönder.⌛",
        "wrong_p12": "Lütfen sadece .p12 dosyasını gönderin!🫣\nTekrar deneyin .p12 dosyasını göndererek devam edin.",
        "send_prov": ".mobileprovision dosyasını gönderin.",
        "wrong_prov": "Geçersiz dosya tipi.🫣!\nLütfen geçerli bir (.mobileProvision) dosyası veya URL'sini gönderin.",
        "downloading_file": "Dosyanız yükleniyor...|📁",
        "send_pass": "Bana şifreyi gönder.🔒\nEğer sertifikanızın şifresi yoksa, (Şifreyi Atla) Düğmesine basın.🔑",
        "skip": "Şifreyi Atla",
        "pass_skipped": "Şifre atlandı!",
        "send_ipa": "IPA dosyanızı iletin veya yükleyin.",
        "wrong_ipa": "Geçersiz dosya tipi.🫣!\nLütfen geçerli bir (.ipa) dosyası gönderin.",
        "signing": "İmzalanıyor. 📝\nBiraz zaman alabilir.",
        "sign_error": "Bir şeyler yanlış gitti.\nHata:\n",
        "upload_failed": "Dosya yüklemesi başarısız oldu! Tekrar deneyin. 🥹",
        "sign_ok": "IPA dosyası imzalandı.🟢\nİndirme Linki 1 hafta geçerlidir.",
        "install": "YÜKLE ✅",
        "thanks": "Kullandığınız için teşekkürler!",
        "timeout": "Zaman aşımı! Baştan başlayın.",
        "send_udid": "Bana UDID'nizi gönderin",
        "invalid_udid": "Hata: geçersiz UDID!",
        "udid_not_found": "Aşağıdaki UDID bizde kayıtlı değil:🤷🏻‍♂️ \nUDID: {udid}",
        "status": "Durum",
        "udid_enabled": "AKTİF 🟢",
        "udid_processing": "İŞLENİYOR 🟠",
        "udid_ineligible": "UYGUN DEĞİL 🔴",
        "register_time": "Kayıt zamanı",
        "activation_time": "Aktivasyon zamanı",
        "checking_udids": "⌛",
        "cert_revoked": "Sertifikanız iptal edildi!🔴 \nFarklı bir sertifika ile tekrar deneyin.",
        "invalid_pass": "Yanlış şifre girdiniz!🔒🥹",
        "unknown_error": "Sertifikanın doğrulanması sırasında bilinmeyen bir hata oluştu.🫣",
        "cert_name": "Sertifika ismi",
        "cert_status": "Durum",
        "cert_date": "Son kullanma tarihi",
        "status_revoked": "İptal edildi 🔴",
        "status_signed": "İmzalandı 🟢",
        "cancel": "İptal.🚪",
        "sign_file": "IPA İMZALA",
        "check_udid": "UDID Denetleyicisi",
        "check_cert": "İptal Denetleyicisi",
        "pick_cert": "Aşağıdan sertifikanızı seçin: ",
        "change_bundle": "Paket Kimliğini Değiştir",
        "additional_opt": "Aşağıdan ek seçenekleri seçin: ",
        "new_bundle": "Rastgele düğmesine basın veya\nistenilen paket kimliğinizi gönderin.",
        "random": "Rastgele",
        "sign_butt": "IPA İMZALA",
        "rm_key": "Klavye kaldırılıyor..",
        "changed_bundle": "Paket Kimliği ayarlandı.✅",
        "etc": "Diğer",
        "get_cert": "Sertifika Al",
        "save_cert": "Sertifika Kaydet",
        "gen_cert": "⏳",
        "gen_err": "Sertifika oluşturulurken bir hata oluştu. 🥹\nLütfen sertifika sağlayıcınıza başvurun.",
        "my_certs": "Sertifikalarım",
        "saved_cert": "Sertifika Sertifikalarım'a kaydedildi.✅",
        "your_cert": "Sertifikalarınız",
        "added_cert": "Sertifika eklendi.✅",
        "back": "Geri",
        "del": "Sil",
        "del_cert": "Sertifika Silindi.🗑️",
        "add": "Ekle",
        "password": "Şifre",
        "skipped": "Atlandı",
        "coupon_count": "Kaç tane Kupon oluşturmamı istersiniz?",
        "reg_udid": "UDID Kaydet",
        "reg_udid_err": "UDID'nizi kaydederken bir hata oluştu.",
        "reg_udid_success": "Başarıyla kaydedildi",
        "send_coupon": "Kuponunuzu gönderin",
        "valid_coupon": "Kupon geçerli!\n Lütfen kaydetmek için bir UDID gönderin.",
        "invalid_coupon": "Kupon kodunuz geçersiz",
        "regd_udid": "Başarıyla kaydedildi!",
        "multi_reg_err": "Aynı anda 1'den fazla UDID kaydetmeye izin verilmez!",
        "digit_err": "Hata, Lütfen bir numara gönderin.",
        "sellect_acct": "Aşağıdaki listeden bir geliştirici hesabı seçin:",
        "gen_coupon": "Kupon Oluştur",
        "list_accounts": "Hesapları Listele",
        "reg_status": "Kayıt durumu",
        "device": "Cihaz"
    },
    "es": {
	"fcert": "Free Cert",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Send your key or buy from @gyke69",
        "start_choice": "Elige una de las opciones a continuación.",
        "lang_choice": "Elige tu idioma:",
        "lang_changed": "¡El idioma ha sido cambiado!",
        "send_p12": "Envíame el archivo .p12.⌛",
        "wrong_p12": "Por favor, envía solo archivos .p12!🫣\nReintentar enviando nuevamente el archivo .p12.",
        "send_prov": "Envía el archivo .mobileprovision.",
        "wrong_prov": "Tipo de archivo inválido.🫣! \nPor favor, envía un archivo válido (.mobileProvision) o su URL.",
        "downloading_file": "Subiendo tu archivo...|📁",
        "send_pass": "Envíame la contraseña.🔒\nSi tu certificado no tiene contraseña, presiona el botón (Omitir Contraseña).🔑",
        "skip": "Omitir Contraseña",
        "pass_skipped": "¡Se ha omitido la contraseña!",
        "send_ipa": "Reenvía o sube tu archivo IPA.",
        "wrong_ipa": "Tipo de archivo inválido.🫣! \nPor favor, envía un archivo válido (.ipa).",
        "signing": "Firmando. 📝\nEsto podría llevar un tiempo.",
        "sign_error": "Algo salió mal.\nError:\n",
        "upload_failed": "¡Error al subir el archivo! Por favor, intenta nuevamente. 🥹",
        "sign_ok": "El archivo IPA ha sido firmado.🟢\nEl enlace de descarga es válido por 1 semana.",
        "install": "INSTALAR ✅",
        "thanks": "¡Gracias por usarlo!",
        "timeout": "¡Tiempo agotado! Por favor, vuelve a intentarlo desde el principio.",
        "send_udid": "Envíame tu UDID",
        "invalid_udid": "Error: ¡UDID inválido!",
        "udid_not_found": "El siguiente UDID no está registrado con nosotros:🤷🏻‍♂️ \nUDID: {udid}",
        "status": "Estado",
        "udid_enabled": "ACTIVO 🟢",
        "udid_processing": "PROCESANDO 🟠",
        "udid_ineligible": "NO APTO 🔴",
        "register_time": "Registrado en",
        "activation_time": "Activa en",
        "checking_udids": "⌛",
        "cert_revoked": "¡Tu certificado ha sido revocado!🔴 \nInténtalo nuevamente con un certificado diferente.",
        "invalid_pass": "¡Has ingresado la contraseña incorrecta!🔒🥹",
        "unknown_error": "Se produjo un error desconocido al verificar el certificado.🫣",
        "cert_name": "Nombre del certificado",
        "cert_status": "Estado",
        "cert_date": "Fecha de expiración",
        "status_revoked": "Revocado 🔴",
        "status_signed": "Firmado 🟢",
        "cancel": "Cancelado.🚪",
        "sign_file": "FIRMAR IPA",
        "check_udid": "Comprobador de UDID",
        "check_cert": "Comprobador de revocación",
        "pick_cert": "Elige tu certificado a continuación: ",
        "change_bundle": "Cambiar BundleID",
        "additional_opt": "Elige opciones adicionales a continuación: ",
        "new_bundle": "Presiona el botón Aleatorio o\nenvía el BundleID deseado.",
        "random": "Aleatorio",
        "sign_butt": "FIRMAR IPA",
        "rm_key": "Eliminando teclado...",
        "changed_bundle": "BundleID establecido.✅",
        "etc": "Otros",
        "get_cert": "Obtener Certificado",
        "save_cert": "Guardar Certificado",
        "gen_cert": "⏳",
        "gen_err": "Se produjo un error al generar el Certificado. 🥹\nPor favor, contacta a tu emisor de Certificados.",
        "my_certs": "Mis Certificados",
        "saved_cert": "Certificado guardado en Mis Certificados.✅",
        "your_cert": "Tus Certificados",
        "added_cert": "Certificado agregado.✅",
        "back": "Volver",
        "del": "Eliminar",
        "del_cert": "Certificado eliminado.🗑️",
        "add": "Agregar",
        "password": "Contraseña",
        "skipped": "Omitido",
        "coupon_count": "¿Cuántos cupones te gustaría que genere?",
        "reg_udid": "Registrar UDID",
        "reg_udid_err": "Se produjo un error al registrar tu UDID.",
        "reg_udid_success": "Registrado exitosamente",
        "send_coupon": "Envía tu cupón",
        "valid_coupon": "¡El cupón es válido! Por favor, envía un UDID para registrarte.",
        "invalid_coupon": "Tu código de cupón es inválido",
        "regd_udid": "Registrado exitosamente",
        "multi_reg_err": "No se te permite registrar más de 1 UDID al mismo tiempo.",
        "digit_err": "Error, por favor, envía un número.",
        "sellect_acct": "Selecciona una cuenta de desarrollador de la siguiente lista:",
        "gen_coupon": "Generar Cupón",
        "list_accounts": "Listar Cuentas",
        "reg_status": "Estado de registro",
        "device": "Dispositivo"
    },
    "zh": {
	"fcert": "Бесплатный сертификат",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Send your key or buy from @gyke69",
        "start_choice": "选择以下选项之一。",
        "lang_choice": "选择您的语言：",
        "lang_changed": "语言已更改！",
        "send_p12": "发送给我.p12文件⌛。",
        "wrong_p12": "请只发送.p12文件！🫣\n继续发送.p12文件以重试。",
        "send_prov": "发送.mobileprovision文件。",
        "wrong_prov": "文件类型无效🫣！\n请发送有效的（.mobileProvision）文件或其URL。",
        "downloading_file": "正在上传您的文件...|📁",
        "send_pass": "发送给我密码🔒。\n如果您的证书没有密码，请点击（跳过密码）按钮🔑。",
        "skip": "跳过密码",
        "pass_skipped": "已跳过密码！",
        "send_ipa": "转发或上传您的IPA文件。",
        "wrong_ipa": "文件类型无效🫣！\n请发送有效的（.ipa）文件。",
        "signing": "正在签名📝。\n这可能需要一些时间。",
        "sign_error": "出了点问题。\n错误：\n",
        "upload_failed": "文件上传失败！请重试🥹。",
        "sign_ok": "IPA文件已签名🟢。\n下载链接在1周内有效。",
        "install": "安装✅",
        "thanks": "感谢您的使用！",
        "timeout": "超时！请从头开始重试。",
        "send_udid": "发送给我您的UDID。",
        "invalid_udid": "错误：无效的UDID！",
        "udid_not_found": "以下UDID没有在我们这里注册🤷🏻♂️ \nUDID：{udid}",
        "status": "状态",
        "udid_enabled": "活跃🟢",
        "udid_processing": "处理中🟠",
        "udid_ineligible": "不符合条件🔴",
        "register_time": "注册时间",
        "activation_time": "激活时间",
        "checking_udids": "⌛",
        "cert_revoked": "您的证书已被撤销！🔴\n请使用不同的证书再试一次。",
        "invalid_pass": "您输入的密码错误！🔒🥹",
        "unknown_error": "在验证证书时发生未知错误🫣。",
        "cert_name": "证书名称",
        "cert_status": "状态",
        "cert_date": "到期日期",
        "status_revoked": "已撤销🔴",
        "status_signed": "已签名🟢",
        "cancel": "已取消🚪",
        "sign_file": "签名IPA",
        "check_udid": "UDID检查器",
        "check_cert": "撤销检查器",
        "pick_cert": "选择下面的证书：",
        "change_bundle": "更改BundleID",
        "additional_opt": "选择下面的额外选项：",
        "new_bundle": "点击随机按钮或\n发送您想要的bundleID。",
        "random": "随机",
        "sign_butt": "签名IPA",
        "rm_key": "移除键盘..",
        "changed_bundle": "已设置BundleID✅",
        "etc": "其他",
        "get_cert": "获取证书",
        "save_cert": "保存证书",
        "gen_cert": "⏳",
        "gen_err": "生成证书时出错🥹\n请联系您的证书颁发机构。",
        "my_certs": "我的证书",
        "saved_cert": "证书已保存到我的证书✅",
        "your_cert": "您的证书",
        "added_cert": "已添加证书✅",
        "back": "返回",
        "del": "删除",
        "del_cert": "证书已删除🗑️",
        "add": "添加",
        "password": "密码",
        "skipped": "已跳过",
        "coupon_count": "您想我为您生成多少优惠券？",
        "reg_udid": "注册UDID",
        "reg_udid_err": "注册您的UDID时发生错误。",
        "reg_udid_success": "成功注册",
        "send_coupon": "发送您的优惠券",
        "valid_coupon": "优惠券有效！\n请发送UDID进行注册。",
        "invalid_coupon": "您的优惠券代码无效",
        "regd_udid": "注册成功！",
        "multi_reg_err": "您不能同时注册多于1个的UDID！",
        "digit_err": "错误，请发送一个数字。",
        "sellect_acct": "从下面的列表中选择一个开发者账户：",
        "gen_coupon": "生成优惠券",
        "list_accounts": "账户列表",
        "reg_status": "注册状态",
        "device": "设备"
    },
    "ar": {
	"fcert": "Бесплатный сертификат",
        "upload_file": "Uploading the file",
        "select_domain": "Select a domain",
        "redirect_title": "Enter channel title",
        "redirect_logo": "Send logo",
        "redirect_link": "send link",
        "redirect_saved": "Data saved!",
        "delete_redirect": "Redirect details deleted.",
        "redirect_details": "API : {api}\nChannel Link : {channel_link}\nChannel Title : {channel_title}\nPlist Logo : {plist_logo}",
        "no_redirect_details":"No details saved!",
        "redirect_plist_logo": "Send me plist logo.\n\nSend /skip if you want to skip.",
        "send_api_key": "Send your key or buy from @gyke69",
        "start_choice": "اختر واحدة من الخيارات أدناه.",
        "lang_choice": "اختر لغتك:",
        "lang_changed": "تم تغيير اللغة!",
        "send_p12": "أرسل لي ملف .p12.⌛",
        "wrong_p12": "الرجاء إرسال ملفات .p12 فقط! 🫣\n حاول مرة أخرى عن طريق متابعة إرسال ملف .p12.",
        "send_prov": "أرسل ملف .mobileprovision.",
        "wrong_prov": "نوع الملف غير صالح.🫣! \n الرجاء إرسال ملف (.mobileProvision) صالح أو URL الخاص به.",
        "downloading_file": "جاري تحميل ملفك...|📁",
        "send_pass": "أرسل لي كلمة المرور.🔒\n إذا كان شهادتك بدون كلمة مرور، اضغط على زر (تخطي كلمة المرور).🔑",
        "skip": "تخطي كلمة المرور",
        "pass_skipped": "تم تخطي كلمة المرور!",
        "send_ipa": "أعد التوجيه أو قم بتحميل ملف IPA الخاص بك.",
        "wrong_ipa": "نوع الملف غير صالح.🫣! \n الرجاء إرسال ملف (.ipa) صالح.",
        "signing": "جار التوقيع عليه. 📝\n قد يستغرق هذا بعض الوقت.",
        "sign_error": "حدث خطأ ما.\n خطأ:\n",
        "upload_failed": "فشل في تحميل الملف! الرجاء المحاولة مرة أخرى. 🥹",
        "sign_ok": "تم توقيع ملف IPA.🟢\n رابط التنزيل صالح لمدة أسبوع.",
        "install": "تثبيت ✅",
        "thanks": "شكراً لاستخدامك له!",
        "timeout": "انتهت المدة! الرجاء المحاولة من البداية.",
        "send_udid": "أرسل لي UDID الخاص بك",
        "invalid_udid": "خطأ: UDID غير صالح!",
        "udid_not_found": "الـUDID التالي غير مسجل لدينا:🤷🏻♂️ \nUDID: {udid}",
        "status": "الحالة",
        "udid_enabled": "نشط 🟢",
        "udid_processing": "جار المعالجة 🟠",
        "udid_ineligible": "غير مؤهل 🔴",
        "register_time": "مسجل في",
        "activation_time": "ينشط في",
        "checking_udids": "⌛",
        "cert_revoked": "تم إلغاء شهادتك!🔴 \n حاول مرة أخرى بشهادة مختلفة.",
        "invalid_pass": "أدخلت كلمة مرور خاطئة!🔒🥹",
        "unknown_error": "حدث خطأ غير معروف أثناء التحقق من الشهادة.🫣",
        "cert_name": "اسم الشهادة",
        "cert_status": "الحالة",
        "cert_date": "تاريخ الانتهاء",
        "status_revoked": "ملغى 🔴",
        "status_signed": "موقع 🟢",
        "cancel": "ألغيت.🚪",
        "sign_file": "وقع IPA",
        "check_udid": "فحص UDID",
        "check_cert": "فحص الإلغاء",
        "pick_cert": "اختر شهادتك من الأسفل: ",
        "change_bundle": "تغيير BundleID",
        "additional_opt": "اختر الخيارات الإضافية أدناه: ",
        "new_bundle": "اضغط على الزر العشوائي أو\n أرسل BundleID المطلوبة.",
        "random": "عشوائي",
        "sign_butt": "وقع IPA",
        "rm_key": "إزالة لوحة المفاتيح..",
        "changed_bundle": "تم تعيين BundleID.✅",
        "etc": "أخرى",
        "get_cert": "احصل على شهادة",
        "save_cert": "حفظ الشهادة",
        "gen_cert": "⏳",
        "gen_err": "حدث خطأ أثناء توليد الشهادة. 🥹\n الرجاء الاتصال بمصدر الشهادة.",
        "my_certs": "شهاداتي",
        "saved_cert": "تم حفظ الشهادة في شهاداتي.✅",
        "your_cert": "شهاداتك",
        "added_cert": "تمت إضافة الشهادة.✅",
        "back": "العودة",
        "del": "حذف",
        "del_cert": "تم حذف الشهادة.🗑️",
        "add": "أضف",
        "password": "كلمة المرور",
        "skipped": "تم التخطي",
        "coupon_count": "كم عدد الكوبونات التي ترغب في أن أنشئها؟",
        "reg_udid":"تسجيل UDID",
        "reg_udid_err": "حدث خطأ أثناء تسجيل UDID الخاص بك.",
        "reg_udid_success": "تم التسجيل بنجاح",
        "send_coupon": "أرسل كوبونك",
        "valid_coupon": "الكوبون صالح!\n الرجاء إرسال UDID للتسجيل.",
        "invalid_coupon": "رمز الكوبون الخاص بك غير صالح",
        "regd_udid": "تم التسجيل بنجاح!",
        "multi_reg_err": "غير مسموح لك بتسجيل أكثر من 1 UDID في نفس الوقت!",
        "digit_err": "خطأ, الرجاء إرسال رقم.",
        "sellect_acct": "اختر حساب المطور من القائمة أدناه:",
        "gen_coupon": "توليد كوبون",
        "list_accounts": "قائمة الحسابات",
        "reg_status": "حالة التسجيل",
        "device": "الجهاز"
    },
}


def get(string_id: str, user_id: int) -> str:
    cursor.execute(f"SELECT lang FROM UsersLangs WHERE id={user_id}")
    try:
        lang = cursor.fetchone()[0]
        return strings[lang][string_id]
    except TypeError:
        return strings["en"][string_id]
